{% set name = "kanga" %}
{% set version = "0.0.19" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: sha256-key

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.3.3
    - numpy >=1.19.2
    - python >=3.6
    - scipy >=1.5.2
    - seaborn >=0.11.0
    - statsmodels >=0.12.0

test:
  imports:
    - kanga

about:
  home: "https://github.com/papamarkou/kanga"
  license: MIT
  license_file: LICENSE.txt
  summary: "MCMC diagnostics"

extra:
  recipe-maintainers:
    - papamarkou
